- hosts: frontend
  vars:
    repository_path: /tmp/wappu-frontend
    nodejs_version: 22.x
  tasks:
    - name: Import the NodeSource GPG key into apt
      become: true
      ansible.builtin.apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x2F59B5F99B1BE0B4
        id: "2f59b5f99b1be0b4"
        state: present  

    - name: Add NodeSource deb repository
      become: true
      ansible.builtin.apt_repository:
        repo: 'deb https://deb.nodesource.com/node_{{ nodejs_version }} nodistro main'
        state: present

    - name: Add NodeSource deb-src repository
      become: true
      ansible.builtin.apt_repository:
        repo: 'deb-src https://deb.nodesource.com/node_{{ nodejs_version }} nodistro main'
        state: present

    - name: Install system dependencies
      become: true
      ansible.builtin.apt:
        update_cache: true
        state: latest
        pkg:
          - git
          - nodejs
          - nginx

    - name: Clone repository
      ansible.builtin.git:
        repo: https://github.com/datalate/wappu-frontend.git
        dest: "{{ repository_path }}"
        accept_newhostkey: true
      register: gitclone

    - name: Install frontend packages
      ansible.builtin.npm:
        path: "{{ repository_path }}"
        ci: true
      when: gitclone.changed

    - name: Build frontend
      ansible.builtin.command: npm run build
      args:
        chdir: "{{ repository_path }}"
      when: gitclone.changed

    - name: Copy built files
      become: true
      ansible.builtin.copy:
        src: "{{ repository_path }}/dist/wappu-frontend/"
        dest: /var/www/wappu
        remote_src: true
        owner: www-data
        group: www-data
        mode: u=rwX,g=rX,o=rX
      when: gitclone.changed

    - name: Add frontend configuration
      become: true
      ansible.builtin.template:
        src: frontend-config.json.j2
        dest: /var/www/wappu/assets/config.json
        owner: www-data
        group: www-data
        mode: u=rwX,g=rX,o=rX
    
    - name: Disable default nginx website
      become: true
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Install nginx website config
      become: true
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/wappu

    - name: Enable nginx website
      become: true
      ansible.builtin.file:
        src: /etc/nginx/sites-available/wappu
        path: /etc/nginx/sites-enabled/wappu
        state: link

    - name: Reload nginx
      become: true
      ansible.builtin.systemd:
        name: nginx
        state: reloaded

- hosts: backend
  vars:
    repository_path: /tmp/wappu-api
    user: wappu
    dotnet_version: 10.0
  tasks:
    - name: Check if MS repository is installed
      ansible.builtin.command: dpkg-query -W packages-microsoft-prod
      register: is_repository_installed
      failed_when: is_repository_installed.rc > 1
      changed_when: is_repository_installed.rc == 1

    - name: Download MS repository
      ansible.builtin.get_url:
        url: 'https://packages.microsoft.com/config/debian/{{ ansible_distribution_major_version }}/packages-microsoft-prod.deb'
        dest: /tmp/packages-microsoft-prod.deb
      when: is_repository_installed.rc == 1

    - name: Install MS repository
      become: true
      ansible.builtin.apt: deb="/tmp/packages-microsoft-prod.deb"
      when: is_repository_installed.rc == 1

    - name: Install dependencies
      become: true
      ansible.builtin.apt:
        update_cache: true
        state: latest
        pkg:
          - git
          - "dotnet-sdk-{{ dotnet_version }}"
          - irssi
          - tmux
          - python3

    - name: Clone repository
      ansible.builtin.git:
        repo: https://github.com/datalate/wappu-api.git
        dest: "{{ repository_path }}"
        accept_newhostkey: true
      register: gitclone

    - name: Restore project
      ansible.builtin.command: dotnet restore
      args:
        chdir: "{{ repository_path }}/WappuApi"
      when: gitclone.changed

    - name: Build project
      ansible.builtin.command: dotnet publish -c Release -o out
      args:
        chdir: "{{ repository_path }}/WappuApi"
      when: gitclone.changed

    - name: Copy built files
      become: true
      ansible.builtin.copy:
        src: "{{ repository_path }}/WappuApi/out/"
        dest: /opt/wappu-api
        remote_src: true
      when: gitclone.changed

    - name: Copy log parser
      become: true
      ansible.builtin.copy:
        src: "{{ repository_path }}/log-parser/"
        dest: /opt/log-parser
        remote_src: true
      when: gitclone.changed

    - name: Copy wappu-api unit file
      become: true
      ansible.builtin.template:
        src: wappu-api.service.j2
        dest: /etc/systemd/user/wappu-api.service
        mode: '644'

    - name: Ensure irssi folder exists
      ansible.builtin.file:
        path: /home/{{ user }}/.irssi
        state: directory

    - name: Copy irssi config file
      ansible.builtin.template:
        src: irssi-config.j2
        dest: /home/{{ user }}/.irssi/config

    - name: Copy irssi unit file
      become: true
      ansible.builtin.template:
        src: irssi.service.j2
        dest: /etc/systemd/user/irssi.service
        mode: '644'
    
    - name: Copy log parser unit file
      become: true
      ansible.builtin.template:
        src: log-parser.service.j2
        dest: /etc/systemd/user/log-parser.service
        mode: '644'
    
    - name: Ensure lingering is enabled
      become: true
      ansible.builtin.command: "loginctl enable-linger {{ user }}"
      args:
        creates: /var/lib/systemd/linger/{{ user }}
    
    - name: Enable wappu-api service
      ansible.builtin.systemd:
        name: wappu-api
        enabled: true
        scope: user
        state: restarted
        daemon_reload: true
    
    - name: Enable irssi service
      ansible.builtin.systemd:
        name: irssi
        enabled: true
        scope: user
        state: started
    
    - name: Enable log parser service
      ansible.builtin.systemd:
        name: log-parser
        enabled: true
        scope: user
        state: started

